"""empty message

Revision ID: 0001
Revises: 
Create Date: 2019-01-07 18:36:39.183406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('previous_block_digest', sa.String(length=52), nullable=False),
    sa.Column('merkle_root', sa.String(length=52), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('transactions_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('number_of_signers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('round', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('block_header_digest', sa.String(length=52), nullable=False),
    sa.Column('main_signer', sa.String(length=52), nullable=False),
    sa.Column('reindex_needed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('digest', sa.String(length=100), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('num_in_block', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('global_num', sa.DECIMAL(precision=22, scale=0), nullable=False),
    sa.Column('is_fee', sa.Boolean(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=19, scale=5), server_default='0', nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100000), nullable=False),
    sa.Column('wallet_from', sa.String(length=52), nullable=True),
    sa.Column('wallet_to', sa.String(length=52), nullable=True),
    sa.Column('mile', sa.DECIMAL(precision=19, scale=5), server_default='0', nullable=False),
    sa.Column('xdr', sa.DECIMAL(precision=19, scale=2), server_default='0', nullable=False),
    sa.Column('asset', sa.SmallInteger(), nullable=True),
    sa.Column('node_address', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=19, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index('transactions__block_id__num_in_block', 'transactions', ['block_id', 'num_in_block'], unique=False)
    op.create_index('transactions__from__timestamp', 'transactions', ['wallet_from', 'timestamp'], unique=False)
    op.create_index('transactions__timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_index('transactions__to__timestamp', 'transactions', ['wallet_to', 'timestamp'], unique=False)
    op.create_table('wallets',
    sa.Column('pub_key', sa.String(length=52), nullable=False),
    sa.Column('tx_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('mile_balance', sa.DECIMAL(precision=19, scale=5), server_default='0', nullable=False),
    sa.Column('mile_staked', sa.DECIMAL(precision=19, scale=5), server_default='0', nullable=False),
    sa.Column('xdr_balance', sa.DECIMAL(precision=19, scale=2), server_default='0', nullable=False),
    sa.Column('xdr_staked', sa.DECIMAL(precision=19, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('balance_updated_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
    sa.Column('update_needed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_node', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('node_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('pub_key')
    )
    op.create_index('transactions__created_at', 'wallets', ['created_at'], unique=False)
    op.create_index('transactions__mile_balance', 'wallets', ['mile_balance'], unique=False)
    op.create_index('transactions__mile_staked', 'wallets', ['mile_staked'], unique=False)
    op.create_index('transactions__update_needed', 'wallets', ['update_needed'], unique=False)
    op.create_index('transactions__xdr_balance', 'wallets', ['xdr_balance'], unique=False)
    op.create_index('transactions__xdr_staked', 'wallets', ['xdr_staked'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transactions__xdr_staked', table_name='wallets')
    op.drop_index('transactions__xdr_balance', table_name='wallets')
    op.drop_index('transactions__update_needed', table_name='wallets')
    op.drop_index('transactions__mile_staked', table_name='wallets')
    op.drop_index('transactions__mile_balance', table_name='wallets')
    op.drop_index('transactions__created_at', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('transactions__to__timestamp', table_name='transactions')
    op.drop_index('transactions__timestamp', table_name='transactions')
    op.drop_index('transactions__from__timestamp', table_name='transactions')
    op.drop_index('transactions__block_id__num_in_block', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('blocks')
    # ### end Alembic commands ###
