"""empty message

Revision ID: 0002
Revises: 0001
Create Date: 2019-01-08 03:02:53.834700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('transactions__block_id__num_in_block__is_fee', 'transactions', ['block_id', 'num_in_block', 'is_fee'], unique=False)
    op.create_index('transactions__is_fee', 'transactions', ['is_fee'], unique=False)
    op.drop_index('transactions__block_id__num_in_block', table_name='transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('transactions__block_id__num_in_block', 'transactions', ['block_id', 'num_in_block'], unique=False)
    op.drop_index('transactions__is_fee', table_name='transactions')
    op.drop_index('transactions__block_id__num_in_block__is_fee', table_name='transactions')
    # ### end Alembic commands ###
