"""empty message

Revision ID: 0004
Revises: 0003
Create Date: 2019-01-13 19:51:15.526153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=0),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False)
    op.alter_column('transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=0),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False)
    op.alter_column('wallets', 'balance_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=0),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=True)
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=0),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=postgresql.TIMESTAMP(timezone=True, precision=0),
               existing_nullable=False)
    op.alter_column('wallets', 'balance_updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=postgresql.TIMESTAMP(timezone=True, precision=0),
               existing_nullable=True)
    op.alter_column('transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=postgresql.TIMESTAMP(timezone=True, precision=0),
               existing_nullable=False)
    op.alter_column('blocks', 'timestamp',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=postgresql.TIMESTAMP(timezone=True, precision=0),
               existing_nullable=False)
    # ### end Alembic commands ###
